import { Router } from 'express';
import * as publicPages from '../controllers/public.js';
import * as aboutPages from '../controllers/about.js';
import * as userPages from '../controllers/users.js';
import * as authHandlers from '../controllers/auth.js';
import { applyInertia } from '../middleware/inertia.js';
import { auth, guest } from '../middleware/auth.js';
import { authRateLimit, featureRateLimit } from '../middleware/rateLimit.js';
const route = Router();
route.use(applyInertia);
route.post(['/login', '/register', '/forgot-password', '/reset-password'], authRateLimit());
route.post('/email/resend-verification', featureRateLimit());
route.get('/login', guest, authHandlers.showLogin);
route.get('/login/admin', guest, authHandlers.loginAsAdmin);
route.post('/login', guest, authHandlers.login);
route.get('/register', guest, authHandlers.showRegister);
route.post('/register', guest, authHandlers.register);
route.get('/forgot-password', guest, authHandlers.showForgotPassword);
route.post('/forgot-password', guest, authHandlers.forgotPassword);
route.get('/reset-password/:token', guest, authHandlers.showResetPassword);
route.post('/reset-password', guest, authHandlers.resetPassword);
route.get('/verify-email', auth, authHandlers.showVerifyEmail);
route.get('/verify-email/:token', auth, authHandlers.verifyEmail);
route.post('/email/resend-verification', auth, authHandlers.resendVerification);
route.get('/', publicPages.index);
route.get('/about', auth, aboutPages.index);
route.get('/home', auth, authHandlers.dashboard);
route.post('/logout', auth, authHandlers.logout);
route.get('/users', auth, userPages.index);
route.get('/users/:id', auth, userPages.show);
export default route;
