// AUTO-GENERATED by scripts/generate-pages.ts. Do not edit by hand.
// Run `npm run pages:generate` to refresh.

const VIEWS = ['About', 'Auth/Login', 'Auth/Register', 'Dashboard', 'Error', 'Home', 'User', 'Users'] as const;

export type PageName = (typeof VIEWS)[number];
